on:
  pull_request:
    types:
      - opened
    branches:
      - 'rc-**'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            console.log('check');
            console.log(github)
            console.log("\n\n\n")
            console.log(context)
